version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  shareit-server:
    build: ./server
    container_name: shareit-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shareit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_SQL_INIT_MODE: always
    depends_on:
      postgres:
        condition: service_healthy

  shareit-gateway:
    build: ./gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      SHAREIT_SERVER_URL: http://shareit-server:9090
    depends_on:
      shareit-server:
        condition: service_started